### ISSUE TITLE
error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by Vanshaj712** [munawarb/Python-Kill-Thread-Extension#11]
I installed the package but when i ran the command - python3 setup.py build

and it invokes-  error: Unable to find vcvarsall.bat .

**Comment by munawarb** [comment]
@Vanshaj712 How did you resolve this issue? An explanation would be much appreciated for future reference. Thanks!

**Comment by Vanshaj712** [comment]
I did nothing but installed the C++ Visual Studio Tools.
