### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by majidmc2** [munawarb/Python-Kill-Thread-Extension#5]
Hi
I runed your code and received an exception

```
import threader
import threading
from time import sleep

class AThread(threading.Thread):
	def run(self):
		while True:
			print("I'm running...and I'll never end!")
			sleep(5)

	def end(self):
		if self.is_alive():
			threader.killThread(self.ident)

runMe = AThread()
runMe.start()
sleep(10)
runMe.end()
```

**exception:**
```
  File "test.py", line 13, in end
    threader.killThread(self.ident)
OverflowError: signed integer is greater than maximum
```

What is problem?

**Comment by munawarb** [comment]
Hi @majidmc2,
Which version of Python and the module are you running? Is it Python2 or Python 3? And is it on Windows or Linux?

**Comment by majidmc2** [comment]
I am using python3.6 and Linux mint 19.

**Comment by munawarb** [comment]
Hi @majidmc2,
I was able to consistently reproduce the problem and have now fixed it. Please clone the repo and try again. Feel free to post here and let me know how it works out for you. Thanks for reporting the problem!
