### ISSUE TITLE
Error with no file pthread.h

### ISSUE THREAD

**Issue by dnikolas** [munawarb/Python-Kill-Thread-Extension#9]
Cant install, have this problem:
threader.c(2): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory

**Comment by munawarb** [comment]
hi @dnikolas,
This is most likely an issue with your setup. It's a default header file.

**Comment by munawarb** [comment]
Hi @dnikolas,
You need to rename threaderPy3windows.c to threader.c. After this, run python setup.py build.

If I try running setup.py with the default threader.c, I get the same error message you described.
